test

diff --git a/.github/workflows/start-azure-resources.yaml b/.github/workflows/start-azure-resources.yaml
--- a/.github/workflows/start-azure-resources.yaml
+++ b/.github/workflows/start-azure-resources.yaml
@@ -49,11 +49,11 @@ jobs:
           az vm list -o table
 
           echo "checking cassandra status"
-          az vm run-command invoke -g FREERG -n Mycassandra --command-id RunShellScript --scripts "/usr/local/cassandra/script.sh" > result.txt
-          cat result.txt | grep "nodetool: Failed to connect"
-          i=$?
+          az vm run-command invoke -g FREERG -n Mycassandra --command-id RunShellScript --scripts "/usr/local/cassandra/script.sh"
+          # cat result.txt | grep "nodetool: Failed to connect"
+          # i=$?
           echo "cassandra status check done"
-          echo "status is : $i"
+          # echo "status is : $i"
 
           # if [ "$?" -eq "0" ]; 
           # then 
